### ISSUE TITLE
add context to all resources

### ISSUE THREAD

**Issue by MichaHoffmann** [aiven/aiven-go-client#125]
Currently the API is not context aware. We could extend it with `[...]WithContext` functions that take a context as first parameter to facilitate cancelation and timeouts.

All API calls without context should be deprecated afterwards.

**Comment by Serpentiel** [comment]
hey, @MichaHoffmann! 👋

currently, our team has not much capacity on adding this functionality since it won't really be used by Aiven's dependent products

if this is getting more community support, this is, however, something that we might consider doing, but in the meantime, please, let us know if this is something that you would like to work on your own

I'll close this as unplanned for now, feel free to reopen this, if needed!

**Comment by Serpentiel** [comment]
completely resolved in #306
